esphome:
  name: "dj-spl-meter"
  friendly_name: "DJ SPL Meter"
  #name_add_mac_suffix: true
  project:
    name: "Guition.ESP32_S3_4848S040"
    version: "1.0.1"
  platformio_options:
    board_build.flash_mode: dio

# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Enable web logging
logger:
  level: DEBUG
  logs:
    esphome: DEBUG
    component: DEBUG
    wifi: DEBUG
    lvgl: DEBUG
    display: DEBUG

# Add number components for thresholds
number:
  - platform: template
    name: "Threshold 1 Low"
    id: threshold_low
    min_value: 50
    max_value: 80
    step: 1
    initial_value: 80
    restore_value: true
    optimistic: true

  - platform: template
    name: "Threshold 2 Medium"
    id: threshold_medium
    min_value: 60
    max_value: 100
    step: 1
    initial_value: 90
    restore_value: true
    optimistic: true

  - platform: template
    name: "Threshold 3 High"
    id: threshold_high
    min_value: 70
    max_value: 110
    step: 1
    initial_value: 96
    restore_value: true
    optimistic: true

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

# Example configuration entry
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# MQTT Client Configuration
mqtt:
  broker: !secret mqtt_broker
  discovery: false # Disable Home Assistant MQTT discovery
  on_connect:
    then:
      - logger.log: "MQTT Connected"
  on_disconnect:
    then:
      - logger.log: "MQTT Disconnected"

  # Subscribe to SPL value topic
  on_message:
    - topic: "spl/value"
      then:
        - sensor.template.publish:
            id: spl_peak
            state: !lambda return atof(x.c_str());
        - sensor.template.publish:
            id: spl_average
            state: !lambda return atof(x.c_str());
        - lvgl.label.update:
            id: current_spl_label
            text: !lambda |-
              static char buf[32];
              snprintf(buf, 32, "%.1f dBA", atof(x.c_str()));
              return buf;
        - lvgl.bar.update:
            id: spl_bar
            value: !lambda |-
              return min(max((float) atof(x.c_str()), 0.0f), 110.0f);

    - topic: "time"
      then:
        - lvgl.label.update:
            id: time_label
            text: !lambda if(x.length() > 0) {
              if(x[0] == '"' && x[x.length()-1] == '"') {
              return x.substr(1, x.length()-2).c_str();
              } else {
              return x.c_str();
              }
              } else {
              return "--:--:--";
              }

web_server:
  port: 80

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 15s
    entity_category: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    on_value:
      - lvgl.label.update:
          id: wifi_label
          text: !lambda |-
            static char buf[32];
            snprintf(buf, 32, "WiFi: %.0fdBm ", id(wifi_signal_db).get_state());
            return buf;

  - platform: template
    name: "SPL Peak"
    id: spl_peak
    unit_of_measurement: "dB"
    filters:
      - max:
          window_size: 50
          send_every: 5
          send_first_at: 1
    on_value:
      - lvgl.label.update:
          id: spl_value_label
          text: !lambda |-
            static char buf[10];
            snprintf(buf, 10, "%.1f", id(spl_peak).get_state());
            return buf;

  - platform: template
    name: "SPL Average"
    id: spl_average
    unit_of_measurement: "dB"
    filters:
      - sliding_window_moving_average:
          window_size: 500
          send_every: 5
    on_value:
      - lvgl.label.update:
          id: average_spl_label
          text: !lambda |-
            static char buf[24];
            snprintf(buf, 24, "%.1f dB Avg (1m)", x);
            return buf;
      - if:
          condition:
            lambda: return x < id(threshold_low).state;
          then:
            - lvgl.update:
                disp_bg_color: 0x000044 # Dark Green
            - lvgl.label.update:
                id: status_label
                text: "Volume Too Low"
          else:
            - if:
                condition:
                  lambda: return x < id(threshold_medium).state;
                then:
                  - lvgl.update:
                      disp_bg_color: 0x00AA00 # Green
                  - lvgl.label.update:
                      id: status_label
                      text: "Volume OK"
                else:
                  - if:
                      condition:
                        lambda: return x < id(threshold_high).state;
                      then:
                        - lvgl.update:
                            disp_bg_color: 0xAA8800 # Orange
                        - lvgl.label.update:
                            id: status_label
                            text: "Volume High"
                      else:
                        - lvgl.update:
                            disp_bg_color: 0x990000 # Red
                        - lvgl.label.update:
                            id: status_label
                            text: "Volume Critical"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: ip_address
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

#-------------------------------------------
#-------------------------------------------
lvgl:
  id: lvgl_comp
  displays:
    - my_display
  touchscreens:
    - touchscreen_id: my_touchscreen

  page_wrap: true
  bg_color: 0x111111
  pages:
    - id: main_page
      skip: false
      layout:
        type: flex
        flex_flow: column_wrap
      width: 480
      height: 480
      bg_color: 0x000000
      bg_opa: 0%
      pad_all: 0
      widgets:
        - label:
            id: wifi_label
            text: "WiFi: ..."
            width: 480
            height: 30
            pad_right: 10
            pad_top: 10
            text_align: right
            text_font: roboto16
            text_color: 0xFFFFFF
            text_opa: 70%
        - label:
            width: 480
            height: 5
            text: " "
        - label:
            id: time_label
            text: "--:--:--"
            y: 80
            width: 480
            height: 40
            text_font: roboto48
            text_align: center
            text_color: 0xFFFFFF
        - label:
            width: 480
            height: 10
            text: " "
        - obj:
            align: CENTER
            width: 480
            height: 30
            scrollable: false
            bg_opa: TRANSP
            border_opa: TRANSP
            layout: # enable the FLEX layout for the children widgets
              type: FLEX
              flex_flow: ROW # the order of the widgets starts top left
              flex_align_cross: CENTER # they sould be centered
            widgets:
              - label:
                  width: 80
                  height: 10
                  text: " "
              - bar:
                  id: spl_bar
                  animated: false
                  width: 300
                  height: 10
                  indicator:
                    bg_color: 0xFFFFFF
                  value: 30
                  min_value: 0
                  max_value: 110
                  bg_color: 0x333333
                  arc_width: 4
                  pad_all: 3
              - label:
                  width: 80
                  height: 10
                  text: " "
        - label:
            id: spl_value_label
            text: "0.0"
            width: 480
            height: 160
            y: 140
            x: 0
            text_align: center
            text_font: font_large
            text_color: 0xFFFFFF
        - label:
            id: spl_unit_label
            text: "dBA (Peak 1m)"
            width: 480
            y: 300
            x: 0
            text_font: roboto24
            text_align: center
            text_color: 0xFFFFFF
            text_opa: 70%
        - label:
            id: status_label
            text_font: roboto24
            text: "Disconnected"
            width: 480
            y: 320
            x: 0
            text_align: center
            text_color: 0xFFFFFF
            text_opa: 70%
        - label:
            width: 480
            height: 10
            text: " "
        - obj:
            align: CENTER
            width: 480
            height: 40
            pad_all: 3
            y: 320
            bg_opa: TRANSP
            scrollable: false
            border_opa: TRANSP
            layout: # enable the FLEX layout for the children widgets
              type: FLEX
              flex_flow: ROW # the order of the widgets starts top left
              flex_align_cross: CENTER # they sould be centered
            widgets:
              - label:
                  id: average_spl_label
                  text: "---.- dBA Avg (1m)"
                  text_align: left
                  text_font: roboto24
                  text_color: 0xFFFFFF
                  width: 240
                  height: 24
                  pad_left: 30
              - label:
                  id: current_spl_label
                  text: "---.- dBA"
                  text_align: right
                  text_font: roboto24
                  text_color: 0xFFFFFF
                  width: 240
                  height: 24
                  pad_right: 50
  on_boot:
    then:
      - lvgl.update:
          disp_bg_color: 0x111111

#-------------------------------------------
# Internal outputs
#-------------------------------------------
output:
  # Backlight LED
  - platform: ledc
    pin: GPIO38
    id: GPIO38
    frequency: 100Hz

#-------------------------------------------
# Internal lights
#-------------------------------------------
light:
  - platform: monochromatic
    output: GPIO38
    name: Backlight
    id: backlight
    restore_mode: ALWAYS_ON

#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
font:
  - file: "gfonts://Roboto"
    id: roboto24
    size: 24
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto48
    size: 48
    bpp: 4
  - file: "gfonts://Roboto"
    id: font_large
    size: 162
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto16
    size: 16
    bpp: 4

#-------------------------------------------
# Touchscreen gt911 i2c
#-------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO19
    scl: GPIO45
    #frequency: 100kHz

touchscreen:
  platform: gt911
  transform:
    mirror_x: false
    mirror_y: false
  id: my_touchscreen
  display: my_display

  on_touch:
    - logger.log:
        format: Touch at (%d, %d)
        args: [touch.x, touch.y]
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
            );
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - light.turn_on: backlight
            - lvgl.resume:
            - lvgl.widget.redraw:
#-------------------------------------------
# Display st7701s spi
#-------------------------------------------
spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

display:
  - platform: st7701s
    id: my_display
    update_interval: never
    auto_clear_enabled: False
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: False
    dimensions:
      width: 480
      height: 480
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: False
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    init_sequence:
      - 1
      # Custom sequences are an array, first byte is command, the rest are data.
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10] # CMD2_BKSEL_BK0
      - [0xCD, 0x00] # disable MDT flag
    data_pins:
      red:
        - 11 #r1
        - 12 #r2
        - 13 #r3
        - 14 #r4
        - 0 #r5
      green:
        - 8 #g0
        - 20 #g1
        - 3 #g2
        - 46 #g3
        - 9 #g4
        - 10 #g5
      blue:
        - 4 #b1
        - 5 #b2
        - 6 #b3
        - 7 #b4
        - 15 #b5
